
#linki ale w postaci zmiennych, movie od 30 do 00 :)
movie30=https://www.youtube.com/watch?v=g0kgw2kkFnM
movie29=https://www.youtube.com/watch?v=MtN1YnoL46Q
movie28=https://www.youtube.com/watch?v=eY52Zsg-KVI&t=35s
movie27=https://www.youtube.com/watch?v=w0AOGeqOnFY
movie26=https://www.youtube.com/watch?v=SB-qEYVdvXA
Movie25=https://www.youtube.com/watch?v=9bZkp7q19f0
movie24=https://www.youtube.com/watch?v=8f7wj_RcqYk
movie23=https://www.youtube.com/watch?v=wZZ7oFKsKzY
movie22=https://www.youtube.com/watch?v=5aC4akD6RUk
movie21=https://www.youtube.com/watch?v=OazsfQiU5k4
movie20=https://www.youtube.com/watch?v=R4nmSUIt4o4
movie19=https://www.youtube.com/watch?v=LXM_tGHcuMo
movie18=https://www.youtube.com/watch?v=O6UBkXLN4PI
movie17=https://www.youtube.com/watch?v=LDU_Txk06tM
movie16=https://www.youtube.com/watch?v=6Dh-RL__uN4
movie15=https://www.youtube.com/watch?v=SUtziaZlDeE
movie14=https://www.youtube.com/watch?v=YZuFsI-bttM
movie13=https://www.youtube.com/watch?v=1415ATwMhvo
movie12=https://www.youtube.com/watch?v=YPiDIWN8YHI
movie11=https://www.youtube.com/watch?v=ty3n87vbVe4
movie10=https://www.youtube.com/watch?v=czgV158MKb8
movie09=https://www.youtube.com/watch?v=3pTH8lb8Rc0
movie08=https://www.youtube.com/watch?v=qYS0EeaAUMw
movie07=https://www.youtube.com/watch?v=cjQQ9JYGgTM
movie06=https://www.youtube.com/watch?v=SiAuAJBZuGs
movie05=https://www.youtube.com/watch?v=kG9KSWYg-Jc
movie04=https://www.youtube.com/watch?v=aNzCDt2eidg
movie03=https://www.youtube.com/watch?v=RgKAFK5djSk
movi302=https://www.youtube.com/watch?v=9E6b3swbnWg
movie01=https://www.youtube.com/watch?v=3yh2InVsFag
movie00=https://www.youtube.com/watch?v=KybAvaM3b90
